name: Master Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker build . -t ghcr.io/<your-username>/<your-repository-name>/project-api:$git_hash

      - name: Test Docker Image
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker run \
          --entrypoint=/bin/bash \
          ghcr.io/<your-username>/<your-repository-name>/project-api:$git_hash \
          ./script/test

      - name: Docker Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GitHub Packages
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker push ghcr.io/<your-username>/<your-repository-name>/project-api:$git_hash
