name: Pull Request CI Pipeline

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker build . -t project-api:$git_hash
      - name: Install httpx
        run: |
          pip install httpx
          
      - name: Run Tests Inside Docker Container
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker run \
          --entrypoint=/bin/bash \
          project-api:$git_hash \
          ./script/test


        