name: Pull Request CI Pipeline

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker build . -t project-api:$git_hash

      # Step 4: Test the Docker Image
      - name: Run Tests Inside Docker Container
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker run \
          --entrypoint=/bin/bash \
          project-api:$git_hash \
          ./script/test


        